# Generated by Django 5.0.4 on 2024-04-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="tenth_grade",
        ),
        migrations.RemoveField(
            model_name="student",
            name="twelfth_grade",
        ),
        migrations.AddField(
            model_name="tenthgrade",
            name="student",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.student",
            ),
        ),
        migrations.AddField(
            model_name="twelfthgrade",
            name="student",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.student",
            ),
        ),
    ]
