# Generated by Django 5.0.4 on 2024-04-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_remove_student_tenth_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenthgrade",
            name="english",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="tenthgrade",
            name="hindi",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="tenthgrade",
            name="math",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="tenthgrade",
            name="science",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="tenthgrade",
            name="social_science",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="twelfthgrade",
            name="chemistry",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="twelfthgrade",
            name="english",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="twelfthgrade",
            name="math",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="twelfthgrade",
            name="other",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="twelfthgrade",
            name="physics",
            field=models.IntegerField(),
        ),
    ]
