# Generated by Django 5.0.4 on 2024-04-04 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registration",
            "0003_alter_tenthgrade_english_alter_tenthgrade_hindi_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenthgrade",
            name="math",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
